config/routes.rb
Rails.application.routes.draw do
  
  resources :health_facilities
  root 'health_facilities#index'

end

app/models/health_facility.rb
class HealthFacility < ActiveRecord::Base
attr_accessible :lat, :longi, :address, :typeOf, :classOf
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/health_facilities_controller.rb
class HealthFacilitiesController < ApplicationController
  before_action :set_health_facility, only: [:show, :edit, :update, :destroy]

  # GET /health_facilities
  # GET /health_facilities.json
  def index
    @health_facilities = HealthFacility.all
    @hash = Gmaps4rails.build_markers(@health_facilities) do |health_facility, marker|
      marker.lat health_facility.lat
      marker.lng health_facility.longi
      marker.infowindow health_facility.typeOf
    end
  end

  # GET /health_facilities/1
  # GET /health_facilities/1.json
  def show
  end

  # GET /health_facilities/new
  def new
    @health_facility = HealthFacility.new
  end

  # GET /health_facilities/1/edit
  def edit
  end

  # POST /health_facilities
  # POST /health_facilities.json
  def create
    @health_facility = HealthFacility.new(health_facility_params)

    respond_to do |format|
      if @health_facility.save
        format.html { redirect_to @health_facility, notice: 'Health facility was successfully created.' }
        format.json { render :show, status: :created, location: @health_facility }
      else
        format.html { render :new }
        format.json { render json: @health_facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /health_facilities/1
  # PATCH/PUT /health_facilities/1.json
  def update
    respond_to do |format|
      if @health_facility.update(health_facility_params)
        format.html { redirect_to @health_facility, notice: 'Health facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @health_facility }
      else
        format.html { render :edit }
        format.json { render json: @health_facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /health_facilities/1
  # DELETE /health_facilities/1.json
  def destroy
    @health_facility.destroy
    respond_to do |format|
      format.html { redirect_to health_facilities_url, notice: 'Health facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  attr_accessor :hash

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health_facility
      @health_facility = HealthFacility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def health_facility_params
      params.require(:health_facility).permit(:lat, :longi, :address, :typeOf, :classOf)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/health_facilities_helper.rb
module HealthFacilitiesHelper
end

app/views/health_facilities/_form.html.erb
<%= form_for(@health_facility, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @health_facility.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@health_facility.errors.count, "error") %> prohibited this health_facility from being saved:</h4>

      <ul>
      <% @health_facility.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :lat, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lat, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longi, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longi, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :typeOf, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :typeOf, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :classOf, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :classOf, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/health_facilities/edit.html.erb
<div class="page-header">
  <%= link_to health_facilities_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @health_facility, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing health_facility</h1>
</div>

<%= render 'form' %>

app/views/health_facilities/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div class="page-header">
  <%= link_to new_health_facility_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Health facility
  <% end %>
  <h1>Listing health_facilities</h1>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Lat</th>
            <th>Longi</th>
            <th>Address</th>
            <th>Typeof</th>
            <th>Classof</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @health_facilities) do |health_facility| %>
            <td><%= health_facility.lat %></td>
            <td><%= health_facility.longi %></td>
            <td><%= health_facility.address %></td>
            <td><%= health_facility.typeOf %></td>
            <td><%= health_facility.classOf %></td>
            <td><%= link_to 'Show', health_facility %></td>
        <td><%= link_to 'Edit', edit_health_facility_path(health_facility) %></td>
        <td><%= link_to 'Destroy', health_facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/health_facilities/new.html.erb
<div class="page-header">
  <%= link_to health_facilities_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New health_facility</h1>
</div>

<%= render 'form' %>

app/views/health_facilities/show.html.erb
<div class="page-header">
  <%= link_to health_facilities_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_health_facility_path(@health_facility), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show health_facility</h1>
</div>

<dl class="dl-horizontal">
  <dt>Lat:</dt>
  <dd><%= @health_facility.lat %></dd>

  <dt>Longi:</dt>
  <dd><%= @health_facility.longi %></dd>

  <dt>Address:</dt>
  <dd><%= @health_facility.address %></dd>

  <dt>Typeof:</dt>
  <dd><%= @health_facility.typeOf %></dd>

  <dt>Classof:</dt>
  <dd><%= @health_facility.classOf %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Smart City Health Care</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Smart City Health Care", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>